# Generated by Django 4.2.11 on 2024-06-03 22:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="addressCustomer",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
