# Generated by Django 4.2.13 on 2024-05-28 23:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopOnline", "0002_item_available_item_description_item_price_and_more"),
    ]

    operations = []
