# Generated by Django 4.2.11 on 2024-06-02 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shopOnline", "0006_categories_item_categorie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="shopOnline.categories",
            ),
        ),
    ]
