# Generated by Django 4.2.11 on 2024-06-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopOnline", "0008_remove_item_categorie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="name",
            field=models.CharField(db_index=True, default=None, max_length=200),
        ),
    ]
