# Generated by Django 4.2.11 on 2024-06-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopOnline", "0011_alter_categories_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categories",
            name="name",
        ),
        migrations.AddField(
            model_name="categories",
            name="na",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
