# Generated by Django 4.2.11 on 2024-06-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopOnline", "0012_remove_categories_name_categories_na"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="na",
            field=models.CharField(
                blank=True, db_index=True, default="csdc", max_length=200
            ),
        ),
    ]
