# Generated by Django 4.2.11 on 2024-06-02 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopOnline", "0013_alter_categories_na"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Categories",
        ),
    ]
