# Generated by Django 4.2.11 on 2024-06-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopOnline", "0014_delete_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "na",
                    models.CharField(
                        blank=True, db_index=True, default="csdc", max_length=200
                    ),
                ),
            ],
        ),
    ]
