# Generated by Django 4.2.11 on 2024-06-02 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shopOnline", "0016_remove_categories_na_categories_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="categories",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="shopOnline.categories",
            ),
        ),
    ]
