# Generated by Django 4.2.11 on 2024-06-03 23:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopOnline", "0017_item_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="quantityAvailable",
        ),
    ]
