# Generated by Django 4.2.11 on 2024-06-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopOnline", "0018_remove_item_quantityavailable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.CharField(db_index=True, default="csdc", max_length=10000),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(db_index=True, max_length=1200),
        ),
    ]
