# Generated by Django 4.2.11 on 2024-06-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopOnline", "0019_alter_item_description_alter_item_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="available",
        ),
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.CharField(blank=True, db_index=True, max_length=10000),
        ),
    ]
