# Generated by Django 4.2.11 on 2024-06-16 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shopOnline", "0019_alter_item_description_alter_item_name"),
        ("comment", "0004_alter_commentitem_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shopOnline.item"
            ),
        ),
    ]
