# Generated by Django 4.2.11 on 2024-06-16 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shopOnline", "0019_alter_item_description_alter_item_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comment", "0006_alter_commentitem_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentitem",
            name="customer",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="commentitem",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shopOnline.item",
            ),
        ),
    ]
