# Generated by Django 4.2.11 on 2024-06-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_order_userorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="noteOrder",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
