# Generated by Django 4.2.11 on 2024-06-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_alter_orderitem_item_alter_orderitem_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.CharField(blank=True, default=0, max_length=200),
        ),
    ]
