# Generated by Django 4.2.11 on 2024-06-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0008_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="totpay",
            field=models.FloatField(blank=True, db_index=True, default=0),
        ),
    ]
