# Generated by Django 4.2.11 on 2024-06-15 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0009_order_totpay"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date",
            field=models.DateField(default=datetime.date(2024, 6, 15)),
        ),
    ]
