# Generated by Django 4.2.11 on 2024-06-15 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0010_order_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="userOrder",
            new_name="customer",
        ),
    ]
