# Generated by Django 4.2.11 on 2024-06-16 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0013_remove_order_customer_order_userorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(default=datetime.date(2024, 6, 16)),
        ),
    ]
