# Generated by Django 4.2.11 on 2024-06-19 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0014_alter_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="stateOrder",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(default=datetime.date(2024, 6, 19)),
        ),
    ]
