# Generated by Django 4.2.11 on 2024-06-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0015_order_stateorder_alter_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="stateItem",
            field=models.BooleanField(default=True),
        ),
    ]
