# Generated by Django 4.2.11 on 2024-06-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0016_orderitem_stateitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="payQuantity",
            field=models.FloatField(blank=True, db_index=True, default=0),
        ),
    ]
